module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'introduction',
        'guiding-principles',
        'faq',
        'ecosystem',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: 'Docs',
      collapsed: false,
      items: ['authoring', 'consuming', 'testing', 'contribution'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/your-first-codemod',
        'guides/understanding-asts',
        'guides/when-not-to-codemod',
        'guides/prompting-for-human-input',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: false,
      items: ['recipes/import-manipulation', 'recipes/react'],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      items: ['api/cli', 'api/utils', 'api/test-utils'],
    },
  ],
  explore: [
    {
      dirName: 'explore',
      type: 'autogenerated',
    },
  ],
};
